# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e46a2e1a4f459e37860339c3df008cdf44025425e14f4191de1c7563ba41bc1e82974c395fb4ad9e94927e6707ef478f378717f81e5cec7670e85736a35fc836

test:
  secret_key_base: 5482b441fae97c8e2f9a0ac83bc1079ee7a6ea194e70a038a54131d1b70a64eb73fc442a82186e423db64cdf3cd6436e07489f46b36f44b08b28fab9042b6d36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
